cuda_visible_devices: 0

data_path: data/beer_advocate.csv # path to csv with structure as in after get_movielens_data(include_time=True)
splitting: 'temporal'

dataloader:
  batch_size: 8
  n_neg_samples: 64

model: 'SASRec' # not used
model_params:
  fwd_type: 'bce' # DO NOT CHANGE
  sampling: 'without_rep'

  maxlen: 200
  hidden_units: 64
  num_blocks: 2
  num_heads: 1
  dropout_rate: 0.3

trainer_params:
  num_epochs: 1000
  patience: 10    # nmb of epoches to wait for improvement in validation metrics
  skip_epochs: 1  # how often to check if validation metrics are improved
  learning_rate: 0.001
  seed: 37
